language: csharp
dotnet: 2.1.300
os:
  - osx
env:
  global:
    - Configuration=Release
install:
  - wget -O MonoGame.pkg "http://teamcity.monogame.net/guestAuth/repository/download/MonoGame_PackageMacAndLinux/.lastSuccessful/MonoGame.pkg?branch_MonoGame=%3Cmaster%3E"
  - sudo installer -pkg "MonoGame.pkg" -target /
script:
  - dotnet build KlSS.csproj
  - dotnet publish -r win-x64 -c release /p:TrimUnusedDependencies=true
  - dotnet publish -r osx-x64 -c release /p:TrimUnusedDependencies=true
  - dotnet publish -r linux-x64 -c release /p:TrimUnusedDependencies=true


