version: 2

.job_configuration: &job_configuration
  docker:
    - image: gmantaos/monogame
  working_directory: ~/repo
  steps:
    - checkout
    - run: dotnet build KlSS.csproj --configuration $BUILDCONFIGURATION
    - run: dotnet publish -r $BUILDPLATFORM --configuration $BUILDCONFIGURATION /p:TrimUnusedDependencies=true
    - store_artifacts:
        path: ~/repo/

jobs:
  windows:
    <<: *job_configuration
    environment:
      BUILDCONFIGURATION: 'release'
      BUILDPLATFORM: 'win-x64'
  linux:
    <<: *job_configuration
    environment:
      BUILDCONFIGURATION: 'release'
      BUILDPLATFORM: 'linux-x64'
  macos:
    <<: *job_configuration
    environment:
      BUILDCONFIGURATION: 'release'
      BUILDPLATFORM: 'osx-x64'
#  deploy:
#    docker:
#      - image: dosowisko/butler
#    steps:
#      - run: butler --help

workflows:
  version: 2
  workflow:
    jobs:
      - windows
      - linux
      - macos
#      - deploy
