version: 2

.job_configuration: &job_configuration
  docker:
    - image: gableroux/dotnet-mono-monogame:latest
  working_directory: ~/repo
  steps:
    - checkout
    - run: ci/build.sh
    - store_artifacts:
        path: ~/repo/artifacts/
jobs:
  windows:
    <<: *job_configuration
    environment:
      BUILD_PLATFORM: 'win-x64'
  linux:
    <<: *job_configuration
    environment:
      BUILD_PLATFORM: 'linux-x64'
  macos:
    <<: *job_configuration
    environment:
      BUILD_PLATFORM: 'osx-x64'
  deploy:
    docker:
      - image: dosowisko/butler:latest
    steps:
      - run: butler --help
      - run: ls -la ~/repo/artifacts
      #- run: butler push ~/repo/artifacts $ITCHIO_USER/$ITCHIO_GAME:$ITCHIO_CHANNEL

workflows:
  version: 2
  workflow:
    jobs:
      - windows
      - linux
      - macos
      - deploy:
        requires:
          - windows
          - linux
          - macos
        filters:
          branches:
            - only:
              - master
              - circleci-deploy-itchio # TODO: delete this line once merge request is merged
    
